"""Restricted TikZ-to-native-Manim compiler and visibility adapters.

The package intentionally supports a documented subset of TikZ. Unsupported
syntax is reported instead of being flattened into SVG or a generic VMobject.
"""

from .compatibility import audit_document_compatibility, load_subset_spec
from .compiler import (
    DocumentSpec,
    IntersectionSpec,
    NamedPathSpec,
    OcclusionRelationSpec,
    ObjectSpec,
    PictureSpec,
    Projection3DSpec,
    TikzNativeCompiler,
    TikzNativeError,
    compile_document,
)
from .fixed_view_renderer import NativeFixedViewRenderer
from .manim_renderer import NativeFigure, NativeManimRenderer
from .manim_renderer_3d import Native3DFigure, NativeManim3DRenderer
from .motion_runtime import (
    MOTION_SCHEMA,
    EllipseChordMetrics,
    MotionConfigError,
    MotionSpec,
    NativeMotionRuntime,
    ellipse_chord_metrics,
    load_motion_spec,
)
from .native_manim_codegen_3d_v3 import (
    NATIVE_MANIM_SOURCE_3D_V3_SCHEMA,
    NativeManimCodegen3DV3Error,
    generate_native_manim_source_3d_v3,
)
from .native_rig_2d import (
    NATIVE_RIG_2D_API_SCHEMA,
    NativeGeometryRig2D,
    NativeRig2D,
)
from .open_face_static_asset_3d import (
    TikzNativeOpenFaceStaticAsset3DError,
    bake_open_face_static_entry_3d,
    validate_open_face_static_asset_3d_contract,
)
from .open_face_visibility_3d_adapter import (
    TikzNativeOpenFaceVisibility3DAdapterError,
    TikzNativeOpenFaceVisibility3DAdapterResult,
    adapt_picture_open_face_visibility_3d,
)
from .open_face_visibility_3d_manim import (
    TikzNativeOpenFaceAutoOcclusion3D,
    bind_picture_open_face_visibility_3d,
)
from .parallel_camera import CameraPlane, ParallelCameraState, ProjectionRank
from .parallel_shots import (
    PARALLEL_CAMERA_SHOT_EASING,
    PARALLEL_CAMERA_SHOT_SEQUENCE_SCHEMA,
    ParallelCameraSafeFrame,
    ParallelCameraShot,
    ParallelCameraShotSequence,
    canonical_parallel_camera_shot_sequence_json,
    fit_points_to_parallel_camera_state,
    parallel_camera_shot_progress,
)
from .parallel_shots_manim import (
    ParallelCameraShotManimError,
    ParallelCameraTargetFollowController,
    play_parallel_camera_shot,
    play_parallel_camera_shot_sequence,
)
from .parallel_frame import (
    ParallelFrameBindingKind,
    ParallelFrameCoordinator,
    ParallelFrameParticipant,
    ParallelFramePhase,
    ParallelFrameState,
    parallel_camera_frame_participant,
)
from .parallel_preflight import (
    PainterOrderEvidence,
    ParallelPreflightLimits,
    ParallelSafeFrame,
    ParallelScreenTransform,
)
from .quadric_section_parallel import (
    SECTION_PLANE_PATCH_CHANNEL,
    ParallelCameraSamplingProvenance,
    ParallelSectionSequence,
    ParallelSectionSequenceError,
    compile_parallel_section_sequence,
    compile_parallel_section_sequence_from_shots,
    parallel_screen_transform_guard,
    parallel_camera_shot_frame_times,
    parallel_section_frame_grid,
    parallel_section_preflight_gate,
    parallel_section_render_times,
    section_display_frame_participant,
    section_plane_patch_participant,
    section_painter_order_participant,
)
from .section_bank_render import (
    SectionBankRenderFrame,
    SectionBankRenderLayer,
    section_bank_frame_participant,
)
from .quadric_section_parallel_manim import (
    ParallelSectionPlaybackError,
    play_parallel_section_sequence,
)
from .polyhedron_visibility_3d_adapter import (
    TikzNativeVisibility3DAdapterError,
    TikzNativeVisibility3DAdapterResult,
    adapt_picture_visibility_3d,
)
from .polyhedron_visibility_3d_manim import (
    TikzNativeAutoOcclusion3D,
    bind_picture_visibility_3d,
)
from .provider import (
    CompiledAsset,
    TikzNativeProviderError,
    compile_asset,
    instantiate_picture,
    provider_info,
    render_static_png,
)
from .version import (
    ASSET_SCHEMA,
    COMPONENT_ASSET_COMPILER,
    COMPONENT_EMBEDDED_MOTION_3D,
    COMPONENT_GEOMETRY_RIG_2D,
    COMPONENT_GEOMETRY_RIG_3D,
    COMPONENT_MOTION_PREVIEW_2D,
    COMPONENT_MOTION_PREVIEW_3D,
    COMPONENT_NATIVE_MANIM_SOURCE_2D,
    COMPONENT_NATIVE_MANIM_SOURCE_3D,
    COMPONENT_NATIVE_MANIM_SOURCE_3D_V2,
    COMPONENT_NATIVE_MANIM_SOURCE_3D_V3,
    COMPONENT_NATIVE_RIG_2D,
    COMPONENT_OPEN_FACE_VISIBILITY,
    COMPONENT_OPEN_FACE_UNIFIED_COMPOSITING,
    COMPONENT_POLYHEDRON_VISIBILITY,
    COMPONENT_REVISION_SCHEMA,
    COMPONENT_TIKZ_OPEN_FACE_STATIC_ASSET_3D,
    COMPONENT_TIKZ_OPEN_FACE_VISIBILITY_3D,
    COMPONENT_TIKZ_POLYHEDRON_VISIBILITY_3D,
    PROTOCOL_VERSION,
    REQUEST_SCHEMA,
    RESPONSE_SCHEMA,
    __version__,
    provider_component_revision,
    provider_component_revisions,
    provider_revision,
)

__all__ = [
    "ASSET_SCHEMA",
    "COMPONENT_ASSET_COMPILER",
    "COMPONENT_EMBEDDED_MOTION_3D",
    "COMPONENT_GEOMETRY_RIG_2D",
    "COMPONENT_GEOMETRY_RIG_3D",
    "COMPONENT_MOTION_PREVIEW_2D",
    "COMPONENT_MOTION_PREVIEW_3D",
    "COMPONENT_NATIVE_MANIM_SOURCE_2D",
    "COMPONENT_NATIVE_MANIM_SOURCE_3D",
    "COMPONENT_NATIVE_MANIM_SOURCE_3D_V2",
    "COMPONENT_NATIVE_MANIM_SOURCE_3D_V3",
    "COMPONENT_NATIVE_RIG_2D",
    "COMPONENT_OPEN_FACE_VISIBILITY",
    "COMPONENT_OPEN_FACE_UNIFIED_COMPOSITING",
    "COMPONENT_POLYHEDRON_VISIBILITY",
    "COMPONENT_REVISION_SCHEMA",
    "COMPONENT_TIKZ_OPEN_FACE_STATIC_ASSET_3D",
    "COMPONENT_TIKZ_OPEN_FACE_VISIBILITY_3D",
    "COMPONENT_TIKZ_POLYHEDRON_VISIBILITY_3D",
    "CompiledAsset",
    "CameraPlane",
    "DocumentSpec",
    "EllipseChordMetrics",
    "IntersectionSpec",
    "MOTION_SCHEMA",
    "MotionConfigError",
    "MotionSpec",
    "NATIVE_MANIM_SOURCE_3D_V3_SCHEMA",
    "NATIVE_RIG_2D_API_SCHEMA",
    "NamedPathSpec",
    "Native3DFigure",
    "NativeFigure",
    "NativeFixedViewRenderer",
    "NativeGeometryRig2D",
    "NativeManim3DRenderer",
    "NativeManimCodegen3DV3Error",
    "NativeManimRenderer",
    "NativeMotionRuntime",
    "NativeRig2D",
    "ObjectSpec",
    "OcclusionRelationSpec",
    "PARALLEL_CAMERA_SHOT_EASING",
    "PARALLEL_CAMERA_SHOT_SEQUENCE_SCHEMA",
    "PROTOCOL_VERSION",
    "ParallelCameraSafeFrame",
    "ParallelCameraShot",
    "ParallelCameraShotManimError",
    "ParallelCameraShotSequence",
    "ParallelCameraState",
    "ParallelCameraSamplingProvenance",
    "ParallelCameraTargetFollowController",
    "ParallelFrameCoordinator",
    "ParallelFrameBindingKind",
    "ParallelFrameParticipant",
    "ParallelFramePhase",
    "ParallelFrameState",
    "ParallelPreflightLimits",
    "ParallelSafeFrame",
    "ParallelScreenTransform",
    "ParallelSectionSequence",
    "ParallelSectionSequenceError",
    "ParallelSectionPlaybackError",
    "PainterOrderEvidence",
    "PictureSpec",
    "Projection3DSpec",
    "ProjectionRank",
    "REQUEST_SCHEMA",
    "RESPONSE_SCHEMA",
    "TikzNativeAutoOcclusion3D",
    "TikzNativeCompiler",
    "TikzNativeError",
    "TikzNativeOpenFaceAutoOcclusion3D",
    "TikzNativeOpenFaceStaticAsset3DError",
    "TikzNativeOpenFaceVisibility3DAdapterError",
    "TikzNativeOpenFaceVisibility3DAdapterResult",
    "TikzNativeProviderError",
    "TikzNativeVisibility3DAdapterError",
    "TikzNativeVisibility3DAdapterResult",
    "__version__",
    "adapt_picture_open_face_visibility_3d",
    "adapt_picture_visibility_3d",
    "audit_document_compatibility",
    "bake_open_face_static_entry_3d",
    "bind_picture_open_face_visibility_3d",
    "bind_picture_visibility_3d",
    "compile_asset",
    "compile_document",
    "canonical_parallel_camera_shot_sequence_json",
    "ellipse_chord_metrics",
    "fit_points_to_parallel_camera_state",
    "generate_native_manim_source_3d_v3",
    "instantiate_picture",
    "load_motion_spec",
    "load_subset_spec",
    "provider_component_revision",
    "provider_component_revisions",
    "provider_info",
    "provider_revision",
    "play_parallel_camera_shot",
    "play_parallel_camera_shot_sequence",
    "play_parallel_section_sequence",
    "parallel_camera_frame_participant",
    "parallel_camera_shot_frame_times",
    "parallel_camera_shot_progress",
    "parallel_screen_transform_guard",
    "parallel_section_frame_grid",
    "parallel_section_preflight_gate",
    "parallel_section_render_times",
    "compile_parallel_section_sequence",
    "compile_parallel_section_sequence_from_shots",
    "SectionBankRenderFrame",
    "SectionBankRenderLayer",
    "SECTION_PLANE_PATCH_CHANNEL",
    "section_bank_frame_participant",
    "section_display_frame_participant",
    "section_plane_patch_participant",
    "section_painter_order_participant",
    "render_static_png",
    "validate_open_face_static_asset_3d_contract",
]
